# Generated by Django 5.1.2 on 2024-12-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('receiver', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='User Name')),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='User Email-ID')),
                ('password', models.CharField(max_length=50, verbose_name='User Password')),
            ],
        ),
    ]
